# Custom stack.yaml for caching shared dependencies across assignments 00 to 05.
resolver: lts-23.11

packages:
  - ./dummy-package

extra-deps:
  - clock-0.8.4
  - dequeue-0.1.12   # Specific to 00-lambda.
  - elsa-0.2.2.0     # Specific to 00-lambda.
  - megaparsec-9.6.1 # Specific to 05-types.

docker:
    enable: false

system-ghc: true

flags: {}

extra-package-dbs: []
